from collections import defaultdict
from datetime import datetime
from json import loads

badges = {
    'colab': 'https://colab.research.google.com/assets/colab-badge.svg',
    'youtube': 'https://upload.wikimedia.org/wikipedia/commons/0/09/YouTube_full-color_icon_%282017%29.svg',
    'git': 'https://upload.wikimedia.org/wikipedia/commons/9/91/Octicons-mark-github.svg',
    'wiki': 'https://upload.wikimedia.org/wikipedia/commons/0/07/Wikipedia_logo_%28svg%29.svg',
    'kaggle': 'https://www.vectorlogo.zone/logos/kaggle/kaggle-icon.svg',
    'arxiv': 'https://web.science.mq.edu.au/~cpurcell/public/images/arxiv_logo.svg', # https://upload.wikimedia.org/wikipedia/commons/a/a8/ArXiv_web.svg
    'tf': 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg',
    'pytorch': 'https://www.vectorlogo.zone/logos/pytorch/pytorch-icon.svg',
    'medium': 'https://upload.vectorlogo.zone/logos/medium/images/43c41ba8-9de2-453d-92dc-500dab4e316a.svg'
}

def colab_url(url):
    return f'[![Open In Colab]({badges["colab"]})]({url})'

def parse_link(link_tuple, height=20):
    name,url = link_tuple
    if name in badges:
        return f'[<img src="{badges[name]}" alt="{name}" height={height}/>]({url})'
        # return f'[![{name}]({badges[name]})](url)'
    return f'[{name}]({url})'

def parse_links(list_of_links):
    if len(list_of_links) == 0:
        return ''
    d = defaultdict(list)
    for name,url in list_of_links:
        d[name].append(url)
    if len(d) == 1:
        return ', '.join(parse_link(link_tuple) for link_tuple in list_of_links)
    return '<ul>' + ''.join('<li>' + ', '.join(parse_link((name, url)) for url in d[name]) + '</li>' for name in d.keys()) + '</ul>'

def generate_table(fn):
    with open(fn, 'r') as infile:
        data = loads(infile.read())
    colabs = sorted(data['colabs'], key=lambda kv: kv['update'], reverse=True)

    print('| name | description | author | links | colaboratory | update |')
    print('|------|-------------|--------|:-----:|:------------:|:------:|')
    for line in colabs:
        if isinstance(line['author'], list):
            line['author'] = '<ul>' + ' '.join(f'<li>{author}</li>' for author in line['author']) + '</ul>'
        line['links'] = parse_links(line['links'])
        line['url'] = colab_url(line['colab'])
        line['update'] = datetime.fromtimestamp(line['update']).strftime('%d.%m.%Y')
        print('| {name} | {description} | {author} | {links} | {url} | {update} |'.format(**line))

def generate_markdown():
    print('# Awesome colab notebooks collection for ML experiments')
    print('## Research')
    generate_table('research.json')
    print('## Tutorials')
    generate_table('tutorials.json')
    print(f'(generated by [{__file__.split("/")[-1]}]({__file__}) based on [research.json](research.json) and [tutorials.json](tutorials.json))')

def main():
    generate_markdown()

if __name__ == '__main__':
    main()